### ISSUE TITLE
Works on iOS but doesn't work on Android

### ISSUE THREAD

**Issue by mediahope** [nghinv-software/react-native-color-wheel#2]
Works on iOS but doesn't work on Android. I can't interact with the Color Wheel and slider in any way, I also had to change the code to make it work on iOS and not swear on hex2Hsv, and I don't need a slider, so I removed it too:

```jsx
import React, { useState } from 'react';
import { View, StyleSheet, Text } from 'react-native';
import { useSharedValue } from 'react-native-reanimated';
import ColorWheel, { ColorAnimated } from '@nghinv/react-native-color-wheel';
import { colors, useHsv } from '@nghinv/react-native-animated';

function App() {
  const [color, setColor] = useState('#0073e5');
  const isGestureActive = useSharedValue(false);
  const hsv = useHsv({
    h: 0,
    s: 0,
    v: 100,
  });



  return (
    <View style={styles.container}>
      <ColorAnimated
        hsv={hsv}
        isGestureActive={isGestureActive}
        style={styles.currentColor}
      />
      <ColorWheel
        hsv={hsv}
        isGestureActive={isGestureActive}
        size={260}
        initialColor={color}
        onColorChange={(value) => {
        setColor(value);
        hsv.value = (value);
        }}
        onColorConfirm={(value) => {
          console.log('onColorConfirm', value);
        }}
      />
      <Text>{color}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  currentColor: {
    width: 80,
    height: 40,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: 'white',
  },
});

export default App;
```

Please, if you can, help me!

**Comment by Nghi-NV** [comment]
you should just use color state or useHsv

```js
function ColorWheelScreen() {
  const isGestureActive = useSharedValue(false);
  const hsv = useHsv({
    h: 0,
    s: 0,
    v: 100,
  });

  useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
    hsv.h.value = hsvValue.h;
    hsv.s.value = hsvValue.s;
    hsv.v.value = hsvValue.v;
  }, [hsv]);

  return (
    <Container>
      <NavBar title="Color Wheel Screen" />
      <View style={styles.container}>
        <ColorAnimated
          hsv={hsv}
          style={styles.currentColor}
          isGestureActive={isGestureActive}
        />
        <ColorWheel
          hsv={hsv}
          isGestureActive={isGestureActive}
          size={260}
          onColorChange={(value) => {
            console.log('onColorChange', value);
          }}
          onColorConfirm={(value) => {
            console.log('onColorConfirm', value);
          }}
        />
      </View>
    </Container>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  currentColor: {
    width: 80,
    height: 40,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: 'white',
  },
});
```

**Comment by nnef** [comment]
Anyway, the Thumb doesn't move on Android, but everything works fine on iOS. I had to change the code again, replaced "Container" with "View", removed "NavBar" and added export default function

'''jsx
import React, { useEffect } from 'react';
import { View, StyleSheet } from 'react-native';
import { useSharedValue } from 'react-native-reanimated';
import ColorWheel, { ColorAnimated } from '@nghinv/react-native-color-wheel';
import { colors, useHsv } from '@nghinv/react-native-animated';

export default function App() {
  const isGestureActive = useSharedValue(false);
  const hsv = useHsv({
    h: 0,
    s: 0,
    v: 100,
  });

  useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
    hsv.h.value = hsvValue.h;
    hsv.s.value = hsvValue.s;
    hsv.v.value = hsvValue.v;
  }, [hsv]);

  return (
    <View>
      <View style={styles.container}>
        <ColorAnimated
          hsv={hsv}
          style={styles.currentColor}
          isGestureActive={isGestureActive}
        />
        <ColorWheel
          hsv={hsv}
          isGestureActive={isGestureActive}
          size={260}
          onColorChange={(value) => {
            console.log('onColorChange', value);
          }}
          onColorConfirm={(value) => {
            console.log('onColorConfirm', value);
          }}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  currentColor: {
    width: 80,
    height: 40,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: 'white',
  },
});
'''

**Comment by mediahope** [comment]
Anyway, the Thumb doesn't move on Android, but everything works fine on iOS. I had to change the code again, replaced "Container" with "View", removed "NavBar" and added export default function

```jsx
import React, { useEffect } from 'react';
import { View, StyleSheet } from 'react-native';
import { useSharedValue } from 'react-native-reanimated';
import ColorWheel, { ColorAnimated } from '@nghinv/react-native-color-wheel';
import { colors, useHsv } from '@nghinv/react-native-animated';

export default function App() {
  const isGestureActive = useSharedValue(false);
  const hsv = useHsv({
    h: 0,
    s: 0,
    v: 100,
  });

  useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
    hsv.h.value = hsvValue.h;
    hsv.s.value = hsvValue.s;
    hsv.v.value = hsvValue.v;
  }, [hsv]);

  return (
    <View>
      <View style={styles.container}>
        <ColorAnimated
          hsv={hsv}
          style={styles.currentColor}
          isGestureActive={isGestureActive}
        />
        <ColorWheel
          hsv={hsv}
          isGestureActive={isGestureActive}
          size={260}
          onColorChange={(value) => {
            console.log('onColorChange', value);
          }}
          onColorConfirm={(value) => {
            console.log('onColorConfirm', value);
          }}
        />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  currentColor: {
    width: 80,
    height: 40,
    borderRadius: 20,
    marginBottom: 24,
    borderWidth: 2,
    borderColor: 'white',
  },
});
```

**Comment by Nghi-NV** [comment]
@nnef what version of react-native-reanimated do you use?
I use this version, it's working well on android
```js
"react-native-reanimated": "^2.3.0-alpha.2",
"react-native-gesture-handler": "^1.10.3",
```

**Comment by mediahope** [comment]
My version:
"react-native-reanimated": "~2.3.1"
Could it be because of the reanimated version?
I will try to reinstall and write

**Comment by mediahope** [comment]
![image](https://user-images.githubusercontent.com/13403919/149331951-ccac4138-15e6-405e-b33b-3619ddf66b4d.png)
![image](https://user-images.githubusercontent.com/13403919/149332004-0cc06465-af81-476b-a0aa-3d73a474a6f7.png)
Such errors come out with the reanimated version 2.3.0-alpha.2

**Comment by mediahope** [comment]
![image](https://user-images.githubusercontent.com/13403919/149386368-faf27f5b-f6aa-4f18-abaf-f584fea891a9.png)
@Nghi-NV This is how it looks on Android, at the same time, I can't move the wheel :(

**Comment by Nghi-NV** [comment]
@dhpro100 you can try this project
https://snack.expo.dev/J5-X2Cpbyq

**Comment by mediahope** [comment]
@Nghi-NV Now everything works as it should! Thank you very much!
![image](https://user-images.githubusercontent.com/13403919/149514521-31005450-aacb-44d9-b244-8c6f6f4641a6.png)
Now I'll do a couple more tests and figure out how to manage it and how to install it into the project anyway)

**Comment by mediahope** [comment]
@Nghi-NV Let me ask you one more question! If I want to take a color from onColorChange, put it as the background of some element, how can I do this? When I put it this way, onColorConfirm always changes to #ffffff
![image](https://user-images.githubusercontent.com/13403919/149517944-e10fb3a0-8984-49ed-a53f-8f4142aea420.png)

**Comment by mediahope** [comment]
@Nghi-NV Can you help me, please?

**Comment by Nghi-NV** [comment]
@dhpro100 you can use function colors.hsv2Hex

<img width="835" alt="image" src="https://user-images.githubusercontent.com/32028055/149654645-dbdc6a54-4345-4d4f-a273-14a1ef0ef404.png">

**Comment by mediahope** [comment]
@Nghi-NV Does not work
I need to use onColorChange values, not onColorConfirm, but when I use the value from onColorChange, whenever there is a setColor (setState) function, when interacting with Color Wheel, the value is sent correctly, but onColorConfirm is reset to the value specified in useEffect. In addition, if I do it this way, as you have shown, I write "no variable found", I have to do setColor.
By the way, when I use the values from onColorConfirm, as you have shown (I also have to pass setColor), exactly the same thing happens, but with animation. Resets to the useEffect value.
I just want to apply the value from onColorChange to the background color of another element.
And I also want to send the value to bluetooth.
But, just this, most likely, will not cause such problems.

**Comment by Nghi-NV** [comment]
@dhpro100 add initialColor={color} to ColorWheel component
```js
function ColorWheelScreen() {
  const [color, setColor] = useState('#ffffff');
  const isGestureActive = useSharedValue(false);
  const hsv = useHsv({
    h: 0,
    s: 0,
    v: 100,
  });

  useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
    hsv.h.value = hsvValue.h;
    hsv.s.value = hsvValue.s;
    hsv.v.value = hsvValue.v;
  }, []);

  return (
    <Container>
      <NavBar title="Color Wheel Screen" />
      <View style={styles.container}>
        <ColorAnimated
          hsv={hsv}
          style={styles.currentColor}
          isGestureActive={isGestureActive}
        />
        <ColorWheel
          hsv={hsv}
          isGestureActive={isGestureActive}
          size={260}
          initialColor={color}
          onColorChange={(value) => {
            console.log('onColorChange', value);
            setColor(value);
          }}
          onColorConfirm={(value) => {
            console.log('onColorConfirm', value);
          }}
        />
      </View>
    </Container>
  );
}
```

**Comment by mediahope** [comment]
@Nghi-NV Same problem, didn't help(
Just returns to the value 0000ff from
```jsx
useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
```

**Comment by Nghi-NV** [comment]
useEffect only render one time
```js
  useEffect(() => {
    const hsvValue = colors.hex2Hsv('#0000ff');
    hsv.h.value = hsvValue.h;
    hsv.s.value = hsvValue.s;
    hsv.v.value = hsvValue.v;
  }, []);
```

**Comment by mediahope** [comment]
> useEffect only render one time
> 
> ```js
>   useEffect(() => {
>     const hsvValue = colors.hex2Hsv('#0000ff');
>     hsv.h.value = hsvValue.h;
>     hsv.s.value = hsvValue.s;
>     hsv.v.value = hsvValue.v;
>   }, []);
> ```

but if setstate appears, then for some reason the color value is always reset to exactly what is indicated there

**Comment by mediahope** [comment]
@Nghi-NV The value is not taken from here, but if, for example, #0000ff is set here, then onColorConfirm will be reset to the value #0000ff
